# Add my Git authentication key from my Work vault
[[ssh-keys]]
item = "Git Authentication Key"
vault = "Work"

# Add my Git signing key from my Work vault
[[ssh-keys]]
item = "Git Signing Key"
vault = "Work"

# Then add all keys from my Private vault
[[ssh-keys]]
vault = "Private"
account = "Einstein Punk Appleseed's Family"